# General
set-option -g default-command "${SHELL} -l"   # Source .bashrc
set-option -g default-command bash            # Run bash on startup
set -g mouse on                               # Enable mouse support
set -g base-index 1                           # Start window numbering at 1
set -g renumber-windows on                    # Renumber windows when one is closed
set -s set-clipboard external                 # Enable System Clipboard
set-option -g status-position top             # Status bar at top
set -g prefix C-s                             # Change leader key to CTRL+S
set -g default-terminal "tmux-256color"       # 256 Colour Support
set -as terminal-overrides ",xterm-kitty:RGB" # 256 Colour Support
set -g allow-passthrough on


# Misc Keybind
unbind p
bind p source-file ~/.tmux.conf              # Create keybind to reload the tmux config

# Copy Mode
set-window-option -g mode-keys vi
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel
unbind -T copy-mode-vi MouseDragEnd1Pane

# Window Management
unbind c
bind -n M-c new-window -a                    # Alt+C opens new window after current
bind -n M-e next-window                      # Alt+E to next window
bind -n M-q previous-window                  # Alt+Q to previous window
bind -n M-C-l next-window                    # Ctrl+Alt+L to next window
bind -n M-C-h previous-window                # Ctrl+Alt+H to previous window

bind M-1 swap-window -t 1                    # Move window to position 1-10
bind M-2 swap-window -t 2
bind M-3 swap-window -t 3
bind M-4 swap-window -t 4
bind M-5 swap-window -t 5
bind M-6 swap-window -t 6
bind M-7 swap-window -t 7
bind M-8 swap-window -t 8
bind M-9 swap-window -t 9
bind M-0 swap-window -t 10

# Pane Management
unbind x
unbind &
bind-key x kill-pane                         # Kill pane without confirmation
bind-key & kill-pane                         # Kill window without confirmation

bind -n M-left select-pane -L                # Alt+Arrow to switch panes
bind -n M-down select-pane -D
bind -n M-up select-pane -U
bind -n M-right select-pane -R

bind -n M-h select-pane -L                   # Alt+hjkl to switch panes
bind -n M-j select-pane -D
bind -n M-k select-pane -U
bind -n M-l select-pane -R

bind -r h swap-pane -U                       # Prefix+h to swap pane upward
bind -r l swap-pane -D                       # Prefix+l to swap pane downward
bind -r k swap-pane -U                       # Prefix+k to swap pane upward
bind -r j swap-pane -D                       # Prefix+j to swap pane downward

# Resizing
bind-key -r C-h resize-pane -L 1             # Leader + Ctrl+hjkl for small resize (1 unit)
bind-key -r C-j resize-pane -D 1
bind-key -r C-k resize-pane -U 1
bind-key -r C-l resize-pane -R 1

bind-key -r M-h resize-pane -L 10            # Leader + Alt+hjkl for large resize (10 units)
bind-key -r M-j resize-pane -D 10
bind-key -r M-k resize-pane -U 10
bind-key -r M-l resize-pane -R 10

# Plugin Configuration
set -g @dracula-plugins "cpu-usage ram-usage"
set -g @tilish-default 'main-vertical'
set -g @override_copy_command 'wl-copy'
set -g @continuum-restore 'on'
set -g @continuum-save-interval '15'

# Plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'jabirali/tmux-tilish'
set -g @plugin 'dracula/tmux'

# Initialise TPM (keep at bottom)
run '~/.tmux/plugins/tpm/tpm'
