preload = ~/Pictures/Wallpapers/Nix.png

wallpaper = eDP-1, ~/Pictures/Wallpapers/Nix.png
wallpaper = DP-9, ~/Pictures/Wallpapers/Nix.png
wallpaper = DP-11, ~/Pictures/Wallpapers/Nix.png

splash = false

