preload = /home/rohaan/Pictures/Wallpapers/Nix.png

wallpaper = eDP-1, /home/rohaan/Pictures/Wallpapers/Nix.png
Wallpaper = DP-9, /home/rohaan/Pictures/Wallpapers/Nix.png
wallpaper = DP-11, /home/rohaan/Pictures/Wallpapers/Nix.png

splash = false
