#preload = /home/rohaan/Pictures/Wallpapers/Nix.png

wallpaper {
  monitor = eDP-1
  path = ~/Pictures/Wallpapers/Nix.png
  fit_mode = cover
}

wallpaper {
  monitor = DP-12
  path = ~/Pictures/Wallpapers/Nix.png
  fit_mode = cover
}

wallpaper {
  monitor = DP-10
  path = ~/Pictures/Wallpapers/Nix.png
  fit_mode = cover
}

splash = false
